// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyTheme(arg1) {
  return window['go']['main']['App']['ApplyTheme'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ListPresets() {
  return window['go']['main']['App']['ListPresets']();
}

export function RestoreOfficial() {
  return window['go']['main']['App']['RestoreOfficial']();
}

export function RevealDataFolder() {
  return window['go']['main']['App']['RevealDataFolder']();
}

export function SelectImage(arg1) {
  return window['go']['main']['App']['SelectImage'](arg1);
}

export function SelectPreset(arg1) {
  return window['go']['main']['App']['SelectPreset'](arg1);
}
