// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyTheme(arg1:main.ThemeConfig):Promise<main.ActionResult>;

export function GetStatus():Promise<main.AppStatus>;

export function ListPresets():Promise<Array<main.PresetBackground>>;

export function RestoreOfficial():Promise<main.ActionResult>;

export function RevealDataFolder():Promise<void>;

export function SelectImage(arg1:string):Promise<main.ImageSelection>;

export function SelectPreset(arg1:string):Promise<main.ImageSelection>;
